spring:
  profiles:
    include:
      - oauth
      - real
#      - real-db

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: password

  session:
    store-type: jdbc

jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect

logging:
  level:
    org.hibernate.SQL: debug
